### ISSUE TITLE
Takes a lot of time matching MathList2 symbols

### ISSUE THREAD

**Issue by kaarmu** [yangwenbo99/typst-lasaveur#2]
Hey :smile: 

On https://github.com/yangwenbo99/typst-lasaveur/blob/master/syntax.py#L99 you have the regex for MatList2, what's the reason for this regex? It takes a lot of time matching and reading it it looks like we can just skip the entire `\zs` and `\ze` parts...

**Comment by yangwenbo99** [comment]
Hi, it seems that your regexes are much more efficient in matching maths.  I don't actually know why I chose to write them in this way....
